# Generated by Django 3.1 on 2020-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='details',
            field=models.TextField(help_text='Add details about the incident', null=True),
        ),
    ]
